// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go_4_vocab_keep/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockWordService is an autogenerated mock type for the WordService type
type MockWordService struct {
	mock.Mock
}

// CreateWord provides a mock function with given fields: ctx, tenantID, req
func (_m *MockWordService) CreateWord(ctx context.Context, tenantID uuid.UUID, req *model.CreateWordRequest) (*model.Word, error) {
	ret := _m.Called(ctx, tenantID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateWord")
	}

	var r0 *model.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.CreateWordRequest) (*model.Word, error)); ok {
		return rf(ctx, tenantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.CreateWordRequest) *model.Word); ok {
		r0 = rf(ctx, tenantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.CreateWordRequest) error); ok {
		r1 = rf(ctx, tenantID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWord provides a mock function with given fields: ctx, tenantID, wordID
func (_m *MockWordService) DeleteWord(ctx context.Context, tenantID uuid.UUID, wordID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, wordID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, wordID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWord provides a mock function with given fields: ctx, tenantID, wordID
func (_m *MockWordService) GetWord(ctx context.Context, tenantID uuid.UUID, wordID uuid.UUID) (*model.Word, error) {
	ret := _m.Called(ctx, tenantID, wordID)

	if len(ret) == 0 {
		panic("no return value specified for GetWord")
	}

	var r0 *model.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Word, error)); ok {
		return rf(ctx, tenantID, wordID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Word); ok {
		r0 = rf(ctx, tenantID, wordID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, wordID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWords provides a mock function with given fields: ctx, tenantID
func (_m *MockWordService) ListWords(ctx context.Context, tenantID uuid.UUID) ([]*model.Word, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for ListWords")
	}

	var r0 []*model.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Word, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Word); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWord provides a mock function with given fields: ctx, tenantID, wordID, req
func (_m *MockWordService) UpdateWord(ctx context.Context, tenantID uuid.UUID, wordID uuid.UUID, req *model.UpdateWordRequest) (*model.Word, error) {
	ret := _m.Called(ctx, tenantID, wordID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWord")
	}

	var r0 *model.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.UpdateWordRequest) (*model.Word, error)); ok {
		return rf(ctx, tenantID, wordID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.UpdateWordRequest) *model.Word); ok {
		r0 = rf(ctx, tenantID, wordID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *model.UpdateWordRequest) error); ok {
		r1 = rf(ctx, tenantID, wordID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockWordService creates a new instance of MockWordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWordService {
	mock := &MockWordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
