// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go_4_vocab_keep/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WordService is an autogenerated mock type for the WordService type
type WordService struct {
	mock.Mock
}

// DeleteWord provides a mock function with given fields: ctx, tenantID, wordID
func (_m *WordService) DeleteWord(ctx context.Context, tenantID uuid.UUID, wordID uuid.UUID) error {
	ret := _m.Called(ctx, tenantID, wordID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, tenantID, wordID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetWord provides a mock function with given fields: ctx, tenantID, wordID
func (_m *WordService) GetWord(ctx context.Context, tenantID uuid.UUID, wordID uuid.UUID) (*model.Word, error) {
	ret := _m.Called(ctx, tenantID, wordID)

	if len(ret) == 0 {
		panic("no return value specified for GetWord")
	}

	var r0 *model.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.Word, error)); ok {
		return rf(ctx, tenantID, wordID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.Word); ok {
		r0 = rf(ctx, tenantID, wordID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID, wordID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWords provides a mock function with given fields: ctx, tenantID
func (_m *WordService) GetWords(ctx context.Context, tenantID uuid.UUID) ([]*model.Word, error) {
	ret := _m.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetWords")
	}

	var r0 []*model.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Word, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Word); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PatchWord provides a mock function with given fields: ctx, tenantID, wordID, req
func (_m *WordService) PatchWord(ctx context.Context, tenantID uuid.UUID, wordID uuid.UUID, req *model.PatchWordRequest) (*model.Word, error) {
	ret := _m.Called(ctx, tenantID, wordID, req)

	if len(ret) == 0 {
		panic("no return value specified for PatchWord")
	}

	var r0 *model.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.PatchWordRequest) (*model.Word, error)); ok {
		return rf(ctx, tenantID, wordID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.PatchWordRequest) *model.Word); ok {
		r0 = rf(ctx, tenantID, wordID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *model.PatchWordRequest) error); ok {
		r1 = rf(ctx, tenantID, wordID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PostWord provides a mock function with given fields: ctx, tenantID, req
func (_m *WordService) PostWord(ctx context.Context, tenantID uuid.UUID, req *model.PostWordRequest) (*model.Word, error) {
	ret := _m.Called(ctx, tenantID, req)

	if len(ret) == 0 {
		panic("no return value specified for PostWord")
	}

	var r0 *model.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.PostWordRequest) (*model.Word, error)); ok {
		return rf(ctx, tenantID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.PostWordRequest) *model.Word); ok {
		r0 = rf(ctx, tenantID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.PostWordRequest) error); ok {
		r1 = rf(ctx, tenantID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PutWord provides a mock function with given fields: ctx, tenantID, wordID, req
func (_m *WordService) PutWord(ctx context.Context, tenantID uuid.UUID, wordID uuid.UUID, req *model.PutWordRequest) (*model.Word, error) {
	ret := _m.Called(ctx, tenantID, wordID, req)

	if len(ret) == 0 {
		panic("no return value specified for PutWord")
	}

	var r0 *model.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.PutWordRequest) (*model.Word, error)); ok {
		return rf(ctx, tenantID, wordID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *model.PutWordRequest) *model.Word); ok {
		r0 = rf(ctx, tenantID, wordID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *model.PutWordRequest) error); ok {
		r1 = rf(ctx, tenantID, wordID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWordService creates a new instance of WordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WordService {
	mock := &WordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
